// This file is auto-generated by @hey-api/openapi-ts

export const $BaseFilter = {
  type: 'object',
  properties: {
    $and: {
      description: 'and查询',
      type: 'array',
      items: {
        $ref: '#/components/schemas/BaseFilter',
      },
    },
    $or: {
      description: 'or查询',
      type: 'array',
      items: {
        $ref: '#/components/schemas/BaseFilter',
      },
    },
    id: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'object',
          properties: {
            $eq: {
              type: 'number',
            },
            $in: {
              type: 'array',
              items: {
                type: 'number',
              },
            },
          },
        },
      ],
    },
    createdAt: {
      anyOf: [
        {
          format: 'date-time',
          type: 'string',
        },
        {
          type: 'object',
          properties: {
            $in: {
              type: 'array',
              items: {
                format: 'date-time',
                type: 'string',
              },
            },
            $eq: {
              format: 'date-time',
              type: 'string',
            },
            $like: {
              format: 'date-time',
              type: 'string',
            },
            $gt: {
              format: 'date-time',
              type: 'string',
            },
            $gte: {
              format: 'date-time',
              type: 'string',
            },
            $lte: {
              format: 'date-time',
              type: 'string',
            },
            $lt: {
              format: 'date-time',
              type: 'string',
            },
          },
        },
      ],
    },
    updateAt: {
      anyOf: [
        {
          format: 'date-time',
          type: 'string',
        },
        {
          type: 'object',
          properties: {
            $in: {
              type: 'array',
              items: {
                format: 'date-time',
                type: 'string',
              },
            },
            $eq: {
              format: 'date-time',
              type: 'string',
            },
            $like: {
              format: 'date-time',
              type: 'string',
            },
            $gt: {
              format: 'date-time',
              type: 'string',
            },
            $gte: {
              format: 'date-time',
              type: 'string',
            },
            $lte: {
              format: 'date-time',
              type: 'string',
            },
            $lt: {
              format: 'date-time',
              type: 'string',
            },
          },
        },
      ],
    },
  },
} as const

export const $UserFilter = {
  type: 'object',
  properties: {
    $and: {
      description: 'and查询',
      type: 'array',
      items: {
        $ref: '#/components/schemas/BaseFilter',
      },
    },
    $or: {
      description: 'or查询',
      type: 'array',
      items: {
        $ref: '#/components/schemas/BaseFilter',
      },
    },
    id: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'object',
          properties: {
            $eq: {
              type: 'number',
            },
            $in: {
              type: 'array',
              items: {
                type: 'number',
              },
            },
          },
        },
      ],
    },
    createdAt: {
      anyOf: [
        {
          format: 'date-time',
          type: 'string',
        },
        {
          type: 'object',
          properties: {
            $in: {
              type: 'array',
              items: {
                format: 'date-time',
                type: 'string',
              },
            },
            $eq: {
              format: 'date-time',
              type: 'string',
            },
            $like: {
              format: 'date-time',
              type: 'string',
            },
            $gt: {
              format: 'date-time',
              type: 'string',
            },
            $gte: {
              format: 'date-time',
              type: 'string',
            },
            $lte: {
              format: 'date-time',
              type: 'string',
            },
            $lt: {
              format: 'date-time',
              type: 'string',
            },
          },
        },
      ],
    },
    updateAt: {
      anyOf: [
        {
          format: 'date-time',
          type: 'string',
        },
        {
          type: 'object',
          properties: {
            $in: {
              type: 'array',
              items: {
                format: 'date-time',
                type: 'string',
              },
            },
            $eq: {
              format: 'date-time',
              type: 'string',
            },
            $like: {
              format: 'date-time',
              type: 'string',
            },
            $gt: {
              format: 'date-time',
              type: 'string',
            },
            $gte: {
              format: 'date-time',
              type: 'string',
            },
            $lte: {
              format: 'date-time',
              type: 'string',
            },
            $lt: {
              format: 'date-time',
              type: 'string',
            },
          },
        },
      ],
    },
    age: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'object',
          properties: {
            $in: {
              type: 'array',
              items: {
                type: 'number',
              },
            },
            $eq: {
              type: 'number',
            },
            $like: {
              type: 'number',
            },
            $gt: {
              type: 'number',
            },
            $gte: {
              type: 'number',
            },
            $lte: {
              type: 'number',
            },
            $lt: {
              type: 'number',
            },
          },
        },
      ],
    },
    account: {
      type: 'object',
    },
  },
} as const

export const $UserOrderBy = {
  type: 'object',
  properties: {
    age: {
      type: 'string',
      enum: ['asc', 'desc'],
    },
    id: {
      type: 'string',
      enum: ['asc', 'desc'],
    },
    createdAt: {
      type: 'string',
      default: 'asc',
      enum: ['asc', 'desc'],
    },
    updateAt: {
      type: 'string',
      enum: ['asc', 'desc'],
    },
  },
} as const
