// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch'
import {
  type AuthControllerCallbackData,
  type AuthControllerCallbackError,
  type AuthControllerCallbackResponse,
  type AuthControllerDevTokenError,
  type AuthControllerDevTokenResponse,
  type AuthControllerProfileError,
  type AuthControllerProfileResponse,
  type AuthControllerLoginData,
  type AuthControllerLoginError,
  type AuthControllerLoginResponse,
  type UserControllerListData,
  type UserControllerListError,
  type UserControllerListResponse,
  type UserControllerGetOneData,
  type UserControllerGetOneError,
  type UserControllerGetOneResponse,
  type UserControllerDeleteData,
  type UserControllerDeleteError,
  type UserControllerDeleteResponse,
  type UserControllerUpdateOneData,
  type UserControllerUpdateOneError,
  type UserControllerUpdateOneResponse,
  type ProjectControllerListData,
  type ProjectControllerListError,
  type ProjectControllerListResponse,
  type ProjectControllerCreateOneData,
  type ProjectControllerCreateOneError,
  type ProjectControllerCreateOneResponse,
  type ProjectControllerMyProjectsData,
  type ProjectControllerMyProjectsError,
  type ProjectControllerMyProjectsResponse,
  type ProjectControllerGetOneData,
  type ProjectControllerGetOneError,
  type ProjectControllerGetOneResponse,
  type ProjectControllerUpdateOneData,
  type ProjectControllerUpdateOneError,
  type ProjectControllerUpdateOneResponse,
  type ProjectControllerDeleteData,
  type ProjectControllerDeleteError,
  type ProjectControllerDeleteResponse,
  type CompanyControllerListData,
  type CompanyControllerListError,
  type CompanyControllerListResponse,
  type CompanyControllerCreateOneData,
  type CompanyControllerCreateOneError,
  type CompanyControllerCreateOneResponse,
  type CompanyControllerMyProjectsData,
  type CompanyControllerMyProjectsError,
  type CompanyControllerMyProjectsResponse,
  type CompanyControllerGetOneData,
  type CompanyControllerGetOneError,
  type CompanyControllerGetOneResponse,
  type CompanyControllerUpdateOneData,
  type CompanyControllerUpdateOneError,
  type CompanyControllerUpdateOneResponse,
  type CompanyControllerDeleteData,
  type CompanyControllerDeleteError,
  type CompanyControllerDeleteResponse,
  type RoleControllerListData,
  type RoleControllerListError,
  type RoleControllerListResponse,
  type RoleControllerCreateOneData,
  type RoleControllerCreateOneError,
  type RoleControllerCreateOneResponse,
  type RoleControllerGetOneData,
  type RoleControllerGetOneError,
  type RoleControllerGetOneResponse,
  type RoleControllerUpdateOneData,
  type RoleControllerUpdateOneError,
  type RoleControllerUpdateOneResponse,
  type RoleControllerDeleteData,
  type RoleControllerDeleteError,
  type RoleControllerDeleteResponse,
  type AccountControllerListData,
  type AccountControllerListError,
  type AccountControllerListResponse,
  type AccountControllerCreateOneData,
  type AccountControllerCreateOneError,
  type AccountControllerCreateOneResponse,
  type AccountControllerMyAccountsData,
  type AccountControllerMyAccountsError,
  type AccountControllerMyAccountsResponse,
  type AccountControllerGetOneData,
  type AccountControllerGetOneError,
  type AccountControllerGetOneResponse,
  type AccountControllerUpdateOneData,
  type AccountControllerUpdateOneError,
  type AccountControllerUpdateOneResponse,
  type AccountControllerDeleteData,
  type AccountControllerDeleteError,
  type AccountControllerDeleteResponse,
  type AccountIncomeControllerListData,
  type AccountIncomeControllerListError,
  type AccountIncomeControllerListResponse,
  type AccountIncomeControllerCreateOneData,
  type AccountIncomeControllerCreateOneError,
  type AccountIncomeControllerCreateOneResponse,
  type AccountIncomeControllerGetOneData,
  type AccountIncomeControllerGetOneError,
  type AccountIncomeControllerGetOneResponse,
  type AccountIncomeControllerUpdateOneData,
  type AccountIncomeControllerUpdateOneError,
  type AccountIncomeControllerUpdateOneResponse,
  type AccountIncomeControllerDeleteData,
  type AccountIncomeControllerDeleteError,
  type AccountIncomeControllerDeleteResponse,
  type ProjectExpensePlanControllerListData,
  type ProjectExpensePlanControllerListError,
  type ProjectExpensePlanControllerListResponse,
  type ProjectExpensePlanControllerCreateOneData,
  type ProjectExpensePlanControllerCreateOneError,
  type ProjectExpensePlanControllerCreateOneResponse,
  type ProjectExpensePlanControllerGetOneData,
  type ProjectExpensePlanControllerGetOneError,
  type ProjectExpensePlanControllerGetOneResponse,
  type ProjectExpensePlanControllerUpdateOneData,
  type ProjectExpensePlanControllerUpdateOneError,
  type ProjectExpensePlanControllerUpdateOneResponse,
  type ProjectExpensePlanControllerDeleteData,
  type ProjectExpensePlanControllerDeleteError,
  type ProjectExpensePlanControllerDeleteResponse,
  type ExpensePlanControllerListData,
  type ExpensePlanControllerListError,
  type ExpensePlanControllerListResponse,
  type ExpensePlanControllerGetOneData,
  type ExpensePlanControllerGetOneError,
  type ExpensePlanControllerGetOneResponse,
  type ExpensePlanControllerUpdateOneData,
  type ExpensePlanControllerUpdateOneError,
  type ExpensePlanControllerUpdateOneResponse,
  type ExpensePlanControllerDeleteData,
  type ExpensePlanControllerDeleteError,
  type ExpensePlanControllerDeleteResponse,
  type PaymentPlanControllerListData,
  type PaymentPlanControllerListError,
  type PaymentPlanControllerListResponse,
  type PaymentPlanControllerCreateOneData,
  type PaymentPlanControllerCreateOneError,
  type PaymentPlanControllerCreateOneResponse,
  type PaymentPlanControllerGetOneData,
  type PaymentPlanControllerGetOneError,
  type PaymentPlanControllerGetOneResponse,
  type PaymentPlanControllerUpdateOneData,
  type PaymentPlanControllerUpdateOneError,
  type PaymentPlanControllerUpdateOneResponse,
  type PaymentPlanControllerDeleteData,
  type PaymentPlanControllerDeleteError,
  type PaymentPlanControllerDeleteResponse,
  type PaymentPlanControllerCreateManyData,
  type PaymentPlanControllerCreateManyError,
  type PaymentPlanControllerCreateManyResponse,
  type PaymentPlanControllerBatchConfirmedData,
  type PaymentPlanControllerBatchConfirmedError,
  type PaymentPlanControllerBatchConfirmedResponse,
  type ActuallyPaymentControllerListData,
  type ActuallyPaymentControllerListError,
  type ActuallyPaymentControllerListResponse,
  type ActuallyPaymentControllerCreateOneData,
  type ActuallyPaymentControllerCreateOneError,
  type ActuallyPaymentControllerCreateOneResponse,
  type ActuallyPaymentControllerGetOneData,
  type ActuallyPaymentControllerGetOneError,
  type ActuallyPaymentControllerGetOneResponse,
  type ActuallyPaymentControllerUpdateOneData,
  type ActuallyPaymentControllerUpdateOneError,
  type ActuallyPaymentControllerUpdateOneResponse,
  type ActuallyPaymentControllerDeleteData,
  type ActuallyPaymentControllerDeleteError,
  type ActuallyPaymentControllerDeleteResponse,
  type ActuallyPaymentControllerConfirmedData,
  type ActuallyPaymentControllerConfirmedError,
  type ActuallyPaymentControllerConfirmedResponse,
  type NonProcessExpenseControllerListData,
  type NonProcessExpenseControllerListError,
  type NonProcessExpenseControllerListResponse,
  type NonProcessExpenseControllerGetOneData,
  type NonProcessExpenseControllerGetOneError,
  type NonProcessExpenseControllerGetOneResponse,
  type NonProcessExpenseControllerCreateManyData,
  type NonProcessExpenseControllerCreateManyError,
  type NonProcessExpenseControllerCreateManyResponse,
  type ExpenseTypeControllerListData,
  type ExpenseTypeControllerListError,
  type ExpenseTypeControllerListResponse,
  type ExpenseTotalControllerTotalByExpenseTypeData,
  type ExpenseTotalControllerTotalByExpenseTypeError,
  type ExpenseTotalControllerTotalByExpenseTypeResponse,
  type ExpenseTotalControllerTotalByProjectData,
  type ExpenseTotalControllerTotalByProjectError,
  type ExpenseTotalControllerTotalByProjectResponse,
  type ExpenseTotalControllerTotalByCompanyData,
  type ExpenseTotalControllerTotalByCompanyError,
  type ExpenseTotalControllerTotalByCompanyResponse,
  type PresaleSupervisionFundsDetailControllerListData,
  type PresaleSupervisionFundsDetailControllerListError,
  type PresaleSupervisionFundsDetailControllerListResponse,
  type PresaleSupervisionFundsDetailControllerSaveData,
  type PresaleSupervisionFundsDetailControllerSaveError,
  type PresaleSupervisionFundsDetailControllerSaveResponse,
  type PresaleSupervisionFundsDetailControllerDeleteData,
  type PresaleSupervisionFundsDetailControllerDeleteError,
  type PresaleSupervisionFundsDetailControllerDeleteResponse,
  type PresaleSupervisionWithdrawableFundsDetailControllerListData,
  type PresaleSupervisionWithdrawableFundsDetailControllerListError,
  type PresaleSupervisionWithdrawableFundsDetailControllerListResponse,
  type PresaleSupervisionWithdrawableFundsDetailControllerSaveData,
  type PresaleSupervisionWithdrawableFundsDetailControllerSaveError,
  type PresaleSupervisionWithdrawableFundsDetailControllerSaveResponse,
  type PresaleSupervisionWithdrawableFundsDetailControllerDeleteData,
  type PresaleSupervisionWithdrawableFundsDetailControllerDeleteError,
  type PresaleSupervisionWithdrawableFundsDetailControllerDeleteResponse,
  AccountIncomeControllerListResponseTransformer,
  AccountIncomeControllerCreateOneResponseTransformer,
  AccountIncomeControllerGetOneResponseTransformer,
  AccountIncomeControllerUpdateOneResponseTransformer,
  PaymentPlanControllerListResponseTransformer,
  PaymentPlanControllerCreateOneResponseTransformer,
  PaymentPlanControllerGetOneResponseTransformer,
  PaymentPlanControllerUpdateOneResponseTransformer,
  PaymentPlanControllerCreateManyResponseTransformer,
  PaymentPlanControllerBatchConfirmedResponseTransformer,
  ActuallyPaymentControllerListResponseTransformer,
  ActuallyPaymentControllerCreateOneResponseTransformer,
  ActuallyPaymentControllerGetOneResponseTransformer,
  ActuallyPaymentControllerUpdateOneResponseTransformer,
  ActuallyPaymentControllerConfirmedResponseTransformer,
} from './types.gen'

export const client = createClient(createConfig())

/**
 * 注册登录快捷方式，仅用于测试
 */
export const authControllerCallback = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerCallbackData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<AuthControllerCallbackResponse, AuthControllerCallbackError, ThrowOnError>({
    ...options,
    url: '/api/auth/callback',
  })
}

export const authControllerDevToken = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<AuthControllerDevTokenResponse, AuthControllerDevTokenError, ThrowOnError>({
    ...options,
    url: '/api/auth/dev-token',
  })
}

/**
 * 用户信息
 */
export const authControllerProfile = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<AuthControllerProfileResponse, AuthControllerProfileError, ThrowOnError>({
    ...options,
    url: '/api/auth/profile',
  })
}

/**
 * 企微授权登录
 */
export const authControllerLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerLoginData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<AuthControllerLoginResponse, AuthControllerLoginError, ThrowOnError>({
    ...options,
    url: '/api/auth/wework-login',
  })
}

/**
 * 列表
 */
export const userControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<UserControllerListData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<UserControllerListResponse, UserControllerListError, ThrowOnError>({
    ...options,
    url: '/api/user',
  })
}

/**
 * item
 */
export const userControllerGetOne = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerGetOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<UserControllerGetOneResponse, UserControllerGetOneError, ThrowOnError>({
    ...options,
    url: '/api/user/{id}',
  })
}

/**
 * 删除
 */
export const userControllerDelete = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerDeleteData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<UserControllerDeleteResponse, UserControllerDeleteError, ThrowOnError>({
    ...options,
    url: '/api/user/{id}',
  })
}

/**
 * 分配用户权限
 */
export const userControllerUpdateOne = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerUpdateOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<UserControllerUpdateOneResponse, UserControllerUpdateOneError, ThrowOnError>(
    {
      ...options,
      url: '/api/user/{id}/assign-permissions',
    },
  )
}

/**
 * 列表
 */
export const projectControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<ProjectControllerListData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<ProjectControllerListResponse, ProjectControllerListError, ThrowOnError>({
    ...options,
    url: '/api/project',
  })
}

/**
 * 新增
 */
export const projectControllerCreateOne = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerCreateOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ProjectControllerCreateOneResponse,
    ProjectControllerCreateOneError,
    ThrowOnError
  >({
    ...options,
    url: '/api/project',
  })
}

/**
 * 有权限的项目列表
 */
export const projectControllerMyProjects = <ThrowOnError extends boolean = false>(
  options?: Options<ProjectControllerMyProjectsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ProjectControllerMyProjectsResponse,
    ProjectControllerMyProjectsError,
    ThrowOnError
  >({
    ...options,
    url: '/api/project/my-projects',
  })
}

/**
 * item
 */
export const projectControllerGetOne = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerGetOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<ProjectControllerGetOneResponse, ProjectControllerGetOneError, ThrowOnError>({
    ...options,
    url: '/api/project/{id}',
  })
}

/**
 * 修改
 */
export const projectControllerUpdateOne = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerUpdateOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    ProjectControllerUpdateOneResponse,
    ProjectControllerUpdateOneError,
    ThrowOnError
  >({
    ...options,
    url: '/api/project/{id}',
  })
}

/**
 * 删除
 */
export const projectControllerDelete = <ThrowOnError extends boolean = false>(
  options: Options<ProjectControllerDeleteData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    ProjectControllerDeleteResponse,
    ProjectControllerDeleteError,
    ThrowOnError
  >({
    ...options,
    url: '/api/project/{id}',
  })
}

/**
 * 列表
 */
export const companyControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<CompanyControllerListData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<CompanyControllerListResponse, CompanyControllerListError, ThrowOnError>({
    ...options,
    url: '/api/company',
  })
}

/**
 * 新增
 */
export const companyControllerCreateOne = <ThrowOnError extends boolean = false>(
  options: Options<CompanyControllerCreateOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CompanyControllerCreateOneResponse,
    CompanyControllerCreateOneError,
    ThrowOnError
  >({
    ...options,
    url: '/api/company',
  })
}

/**
 * 有权限的企业列表
 */
export const companyControllerMyProjects = <ThrowOnError extends boolean = false>(
  options?: Options<CompanyControllerMyProjectsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    CompanyControllerMyProjectsResponse,
    CompanyControllerMyProjectsError,
    ThrowOnError
  >({
    ...options,
    url: '/api/company/my-companies',
  })
}

/**
 * item
 */
export const companyControllerGetOne = <ThrowOnError extends boolean = false>(
  options: Options<CompanyControllerGetOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<CompanyControllerGetOneResponse, CompanyControllerGetOneError, ThrowOnError>({
    ...options,
    url: '/api/company/{id}',
  })
}

/**
 * 修改
 */
export const companyControllerUpdateOne = <ThrowOnError extends boolean = false>(
  options: Options<CompanyControllerUpdateOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    CompanyControllerUpdateOneResponse,
    CompanyControllerUpdateOneError,
    ThrowOnError
  >({
    ...options,
    url: '/api/company/{id}',
  })
}

/**
 * 删除
 */
export const companyControllerDelete = <ThrowOnError extends boolean = false>(
  options: Options<CompanyControllerDeleteData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    CompanyControllerDeleteResponse,
    CompanyControllerDeleteError,
    ThrowOnError
  >({
    ...options,
    url: '/api/company/{id}',
  })
}

/**
 * 列表
 */
export const roleControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<RoleControllerListData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<RoleControllerListResponse, RoleControllerListError, ThrowOnError>({
    ...options,
    url: '/api/role',
  })
}

/**
 * 新增
 */
export const roleControllerCreateOne = <ThrowOnError extends boolean = false>(
  options: Options<RoleControllerCreateOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<RoleControllerCreateOneResponse, RoleControllerCreateOneError, ThrowOnError>({
    ...options,
    url: '/api/role',
  })
}

/**
 * item
 */
export const roleControllerGetOne = <ThrowOnError extends boolean = false>(
  options: Options<RoleControllerGetOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<RoleControllerGetOneResponse, RoleControllerGetOneError, ThrowOnError>({
    ...options,
    url: '/api/role/{id}',
  })
}

/**
 * 修改
 */
export const roleControllerUpdateOne = <ThrowOnError extends boolean = false>(
  options: Options<RoleControllerUpdateOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<RoleControllerUpdateOneResponse, RoleControllerUpdateOneError, ThrowOnError>(
    {
      ...options,
      url: '/api/role/{id}',
    },
  )
}

/**
 * 删除
 */
export const roleControllerDelete = <ThrowOnError extends boolean = false>(
  options: Options<RoleControllerDeleteData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<RoleControllerDeleteResponse, RoleControllerDeleteError, ThrowOnError>({
    ...options,
    url: '/api/role/{id}',
  })
}

/**
 * 列表
 */
export const accountControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<AccountControllerListData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<AccountControllerListResponse, AccountControllerListError, ThrowOnError>({
    ...options,
    url: '/api/account',
  })
}

/**
 * 新增
 */
export const accountControllerCreateOne = <ThrowOnError extends boolean = false>(
  options: Options<AccountControllerCreateOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AccountControllerCreateOneResponse,
    AccountControllerCreateOneError,
    ThrowOnError
  >({
    ...options,
    url: '/api/account',
  })
}

/**
 * 有权限的账户列表
 */
export const accountControllerMyAccounts = <ThrowOnError extends boolean = false>(
  options?: Options<AccountControllerMyAccountsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AccountControllerMyAccountsResponse,
    AccountControllerMyAccountsError,
    ThrowOnError
  >({
    ...options,
    url: '/api/account/my-accounts',
  })
}

/**
 * item
 */
export const accountControllerGetOne = <ThrowOnError extends boolean = false>(
  options: Options<AccountControllerGetOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<AccountControllerGetOneResponse, AccountControllerGetOneError, ThrowOnError>({
    ...options,
    url: '/api/account/{id}',
  })
}

/**
 * 修改
 */
export const accountControllerUpdateOne = <ThrowOnError extends boolean = false>(
  options: Options<AccountControllerUpdateOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    AccountControllerUpdateOneResponse,
    AccountControllerUpdateOneError,
    ThrowOnError
  >({
    ...options,
    url: '/api/account/{id}',
  })
}

/**
 * 删除
 */
export const accountControllerDelete = <ThrowOnError extends boolean = false>(
  options: Options<AccountControllerDeleteData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    AccountControllerDeleteResponse,
    AccountControllerDeleteError,
    ThrowOnError
  >({
    ...options,
    url: '/api/account/{id}',
  })
}

/**
 * 列表
 */
export const accountIncomeControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<AccountIncomeControllerListData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AccountIncomeControllerListResponse,
    AccountIncomeControllerListError,
    ThrowOnError
  >({
    ...options,
    url: '/api/account-income',
    responseTransformer: AccountIncomeControllerListResponseTransformer,
  })
}

/**
 * 新增
 */
export const accountIncomeControllerCreateOne = <ThrowOnError extends boolean = false>(
  options: Options<AccountIncomeControllerCreateOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AccountIncomeControllerCreateOneResponse,
    AccountIncomeControllerCreateOneError,
    ThrowOnError
  >({
    ...options,
    url: '/api/account-income',
    responseTransformer: AccountIncomeControllerCreateOneResponseTransformer,
  })
}

/**
 * item
 */
export const accountIncomeControllerGetOne = <ThrowOnError extends boolean = false>(
  options: Options<AccountIncomeControllerGetOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AccountIncomeControllerGetOneResponse,
    AccountIncomeControllerGetOneError,
    ThrowOnError
  >({
    ...options,
    url: '/api/account-income/{id}',
    responseTransformer: AccountIncomeControllerGetOneResponseTransformer,
  })
}

/**
 * 修改
 */
export const accountIncomeControllerUpdateOne = <ThrowOnError extends boolean = false>(
  options: Options<AccountIncomeControllerUpdateOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    AccountIncomeControllerUpdateOneResponse,
    AccountIncomeControllerUpdateOneError,
    ThrowOnError
  >({
    ...options,
    url: '/api/account-income/{id}',
    responseTransformer: AccountIncomeControllerUpdateOneResponseTransformer,
  })
}

/**
 * 删除
 */
export const accountIncomeControllerDelete = <ThrowOnError extends boolean = false>(
  options: Options<AccountIncomeControllerDeleteData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    AccountIncomeControllerDeleteResponse,
    AccountIncomeControllerDeleteError,
    ThrowOnError
  >({
    ...options,
    url: '/api/account-income/{id}',
  })
}

/**
 * 列表
 */
export const projectExpensePlanControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<ProjectExpensePlanControllerListData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ProjectExpensePlanControllerListResponse,
    ProjectExpensePlanControllerListError,
    ThrowOnError
  >({
    ...options,
    url: '/api/project-expense-plan',
  })
}

/**
 * 新增
 */
export const projectExpensePlanControllerCreateOne = <ThrowOnError extends boolean = false>(
  options: Options<ProjectExpensePlanControllerCreateOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ProjectExpensePlanControllerCreateOneResponse,
    ProjectExpensePlanControllerCreateOneError,
    ThrowOnError
  >({
    ...options,
    url: '/api/project-expense-plan',
  })
}

/**
 * item
 */
export const projectExpensePlanControllerGetOne = <ThrowOnError extends boolean = false>(
  options: Options<ProjectExpensePlanControllerGetOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ProjectExpensePlanControllerGetOneResponse,
    ProjectExpensePlanControllerGetOneError,
    ThrowOnError
  >({
    ...options,
    url: '/api/project-expense-plan/{id}',
  })
}

/**
 * 修改
 */
export const projectExpensePlanControllerUpdateOne = <ThrowOnError extends boolean = false>(
  options: Options<ProjectExpensePlanControllerUpdateOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    ProjectExpensePlanControllerUpdateOneResponse,
    ProjectExpensePlanControllerUpdateOneError,
    ThrowOnError
  >({
    ...options,
    url: '/api/project-expense-plan/{id}',
  })
}

/**
 * 删除
 */
export const projectExpensePlanControllerDelete = <ThrowOnError extends boolean = false>(
  options: Options<ProjectExpensePlanControllerDeleteData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    ProjectExpensePlanControllerDeleteResponse,
    ProjectExpensePlanControllerDeleteError,
    ThrowOnError
  >({
    ...options,
    url: '/api/project-expense-plan/{id}',
  })
}

/**
 * 列表
 */
export const expensePlanControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<ExpensePlanControllerListData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ExpensePlanControllerListResponse,
    ExpensePlanControllerListError,
    ThrowOnError
  >({
    ...options,
    url: '/api/expense-plan',
  })
}

/**
 * item
 */
export const expensePlanControllerGetOne = <ThrowOnError extends boolean = false>(
  options: Options<ExpensePlanControllerGetOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ExpensePlanControllerGetOneResponse,
    ExpensePlanControllerGetOneError,
    ThrowOnError
  >({
    ...options,
    url: '/api/expense-plan/{id}',
  })
}

/**
 * 修改
 */
export const expensePlanControllerUpdateOne = <ThrowOnError extends boolean = false>(
  options: Options<ExpensePlanControllerUpdateOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    ExpensePlanControllerUpdateOneResponse,
    ExpensePlanControllerUpdateOneError,
    ThrowOnError
  >({
    ...options,
    url: '/api/expense-plan/{id}',
  })
}

/**
 * 删除
 */
export const expensePlanControllerDelete = <ThrowOnError extends boolean = false>(
  options: Options<ExpensePlanControllerDeleteData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    ExpensePlanControllerDeleteResponse,
    ExpensePlanControllerDeleteError,
    ThrowOnError
  >({
    ...options,
    url: '/api/expense-plan/{id}',
  })
}

/**
 * 列表
 */
export const paymentPlanControllerList = <ThrowOnError extends boolean = false>(
  options: Options<PaymentPlanControllerListData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PaymentPlanControllerListResponse,
    PaymentPlanControllerListError,
    ThrowOnError
  >({
    ...options,
    url: '/api/payment-plan/{expensePlanId}',
    responseTransformer: PaymentPlanControllerListResponseTransformer,
  })
}

/**
 * 新增
 */
export const paymentPlanControllerCreateOne = <ThrowOnError extends boolean = false>(
  options: Options<PaymentPlanControllerCreateOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PaymentPlanControllerCreateOneResponse,
    PaymentPlanControllerCreateOneError,
    ThrowOnError
  >({
    ...options,
    url: '/api/payment-plan/{expensePlanId}',
    responseTransformer: PaymentPlanControllerCreateOneResponseTransformer,
  })
}

/**
 * item
 */
export const paymentPlanControllerGetOne = <ThrowOnError extends boolean = false>(
  options: Options<PaymentPlanControllerGetOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PaymentPlanControllerGetOneResponse,
    PaymentPlanControllerGetOneError,
    ThrowOnError
  >({
    ...options,
    url: '/api/payment-plan/{expensePlanId}/{id}',
    responseTransformer: PaymentPlanControllerGetOneResponseTransformer,
  })
}

/**
 * 修改
 */
export const paymentPlanControllerUpdateOne = <ThrowOnError extends boolean = false>(
  options: Options<PaymentPlanControllerUpdateOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    PaymentPlanControllerUpdateOneResponse,
    PaymentPlanControllerUpdateOneError,
    ThrowOnError
  >({
    ...options,
    url: '/api/payment-plan/{expensePlanId}/{id}',
    responseTransformer: PaymentPlanControllerUpdateOneResponseTransformer,
  })
}

/**
 * 删除
 */
export const paymentPlanControllerDelete = <ThrowOnError extends boolean = false>(
  options: Options<PaymentPlanControllerDeleteData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    PaymentPlanControllerDeleteResponse,
    PaymentPlanControllerDeleteError,
    ThrowOnError
  >({
    ...options,
    url: '/api/payment-plan/{expensePlanId}/{id}',
  })
}

/**
 * 批量新增
 */
export const paymentPlanControllerCreateMany = <ThrowOnError extends boolean = false>(
  options: Options<PaymentPlanControllerCreateManyData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PaymentPlanControllerCreateManyResponse,
    PaymentPlanControllerCreateManyError,
    ThrowOnError
  >({
    ...options,
    url: '/api/payment-plan/{expensePlanId}/batch-create',
    responseTransformer: PaymentPlanControllerCreateManyResponseTransformer,
  })
}

/**
 * 批量确认计划
 */
export const paymentPlanControllerBatchConfirmed = <ThrowOnError extends boolean = false>(
  options: Options<PaymentPlanControllerBatchConfirmedData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    PaymentPlanControllerBatchConfirmedResponse,
    PaymentPlanControllerBatchConfirmedError,
    ThrowOnError
  >({
    ...options,
    url: '/api/payment-plan/{expensePlanId}/batch-confirmed',
    responseTransformer: PaymentPlanControllerBatchConfirmedResponseTransformer,
  })
}

/**
 * 列表
 */
export const actuallyPaymentControllerList = <ThrowOnError extends boolean = false>(
  options: Options<ActuallyPaymentControllerListData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ActuallyPaymentControllerListResponse,
    ActuallyPaymentControllerListError,
    ThrowOnError
  >({
    ...options,
    url: '/api/actually-payment/{paymentPlanId}',
    responseTransformer: ActuallyPaymentControllerListResponseTransformer,
  })
}

/**
 * 新增
 */
export const actuallyPaymentControllerCreateOne = <ThrowOnError extends boolean = false>(
  options: Options<ActuallyPaymentControllerCreateOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ActuallyPaymentControllerCreateOneResponse,
    ActuallyPaymentControllerCreateOneError,
    ThrowOnError
  >({
    ...options,
    url: '/api/actually-payment/{paymentPlanId}',
    responseTransformer: ActuallyPaymentControllerCreateOneResponseTransformer,
  })
}

/**
 * item
 */
export const actuallyPaymentControllerGetOne = <ThrowOnError extends boolean = false>(
  options: Options<ActuallyPaymentControllerGetOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ActuallyPaymentControllerGetOneResponse,
    ActuallyPaymentControllerGetOneError,
    ThrowOnError
  >({
    ...options,
    url: '/api/actually-payment/{paymentPlanId}/{id}',
    responseTransformer: ActuallyPaymentControllerGetOneResponseTransformer,
  })
}

/**
 * 修改
 */
export const actuallyPaymentControllerUpdateOne = <ThrowOnError extends boolean = false>(
  options: Options<ActuallyPaymentControllerUpdateOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    ActuallyPaymentControllerUpdateOneResponse,
    ActuallyPaymentControllerUpdateOneError,
    ThrowOnError
  >({
    ...options,
    url: '/api/actually-payment/{paymentPlanId}/{id}',
    responseTransformer: ActuallyPaymentControllerUpdateOneResponseTransformer,
  })
}

/**
 * 删除
 */
export const actuallyPaymentControllerDelete = <ThrowOnError extends boolean = false>(
  options: Options<ActuallyPaymentControllerDeleteData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    ActuallyPaymentControllerDeleteResponse,
    ActuallyPaymentControllerDeleteError,
    ThrowOnError
  >({
    ...options,
    url: '/api/actually-payment/{paymentPlanId}/{id}',
  })
}

/**
 * 确认付款
 */
export const actuallyPaymentControllerConfirmed = <ThrowOnError extends boolean = false>(
  options: Options<ActuallyPaymentControllerConfirmedData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    ActuallyPaymentControllerConfirmedResponse,
    ActuallyPaymentControllerConfirmedError,
    ThrowOnError
  >({
    ...options,
    url: '/api/actually-payment/{paymentPlanId}/{id}/confirmed',
    responseTransformer: ActuallyPaymentControllerConfirmedResponseTransformer,
  })
}

/**
 * 列表
 */
export const nonProcessExpenseControllerList = <ThrowOnError extends boolean = false>(
  options: Options<NonProcessExpenseControllerListData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    NonProcessExpenseControllerListResponse,
    NonProcessExpenseControllerListError,
    ThrowOnError
  >({
    ...options,
    url: '/api/non-process-expense/{accountId}',
  })
}

/**
 * item
 */
export const nonProcessExpenseControllerGetOne = <ThrowOnError extends boolean = false>(
  options: Options<NonProcessExpenseControllerGetOneData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    NonProcessExpenseControllerGetOneResponse,
    NonProcessExpenseControllerGetOneError,
    ThrowOnError
  >({
    ...options,
    url: '/api/non-process-expense/{accountId}/{id}',
  })
}

/**
 * 批量保存
 */
export const nonProcessExpenseControllerCreateMany = <ThrowOnError extends boolean = false>(
  options: Options<NonProcessExpenseControllerCreateManyData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    NonProcessExpenseControllerCreateManyResponse,
    NonProcessExpenseControllerCreateManyError,
    ThrowOnError
  >({
    ...options,
    url: '/api/non-process-expense/{accountId}/save',
  })
}

/**
 * 列表
 */
export const expenseTypeControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<ExpenseTypeControllerListData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ExpenseTypeControllerListResponse,
    ExpenseTypeControllerListError,
    ThrowOnError
  >({
    ...options,
    url: '/api/expense-type',
  })
}

/**
 * 按支出类型汇总
 */
export const expenseTotalControllerTotalByExpenseType = <ThrowOnError extends boolean = false>(
  options?: Options<ExpenseTotalControllerTotalByExpenseTypeData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ExpenseTotalControllerTotalByExpenseTypeResponse,
    ExpenseTotalControllerTotalByExpenseTypeError,
    ThrowOnError
  >({
    ...options,
    url: '/api/expense-total/total/by-expense-type',
  })
}

/**
 * 按项目汇总
 */
export const expenseTotalControllerTotalByProject = <ThrowOnError extends boolean = false>(
  options?: Options<ExpenseTotalControllerTotalByProjectData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ExpenseTotalControllerTotalByProjectResponse,
    ExpenseTotalControllerTotalByProjectError,
    ThrowOnError
  >({
    ...options,
    url: '/api/expense-total/total/by-project',
  })
}

/**
 * 按企业汇总
 */
export const expenseTotalControllerTotalByCompany = <ThrowOnError extends boolean = false>(
  options?: Options<ExpenseTotalControllerTotalByCompanyData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ExpenseTotalControllerTotalByCompanyResponse,
    ExpenseTotalControllerTotalByCompanyError,
    ThrowOnError
  >({
    ...options,
    url: '/api/expense-total/total/by-company',
  })
}

/**
 * 列表
 */
export const presaleSupervisionFundsDetailControllerList = <ThrowOnError extends boolean = false>(
  options: Options<PresaleSupervisionFundsDetailControllerListData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PresaleSupervisionFundsDetailControllerListResponse,
    PresaleSupervisionFundsDetailControllerListError,
    ThrowOnError
  >({
    ...options,
    url: '/api/presale-supervision-funds-detail/{projectId}',
  })
}

/**
 * 批量保存
 */
export const presaleSupervisionFundsDetailControllerSave = <ThrowOnError extends boolean = false>(
  options: Options<PresaleSupervisionFundsDetailControllerSaveData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PresaleSupervisionFundsDetailControllerSaveResponse,
    PresaleSupervisionFundsDetailControllerSaveError,
    ThrowOnError
  >({
    ...options,
    url: '/api/presale-supervision-funds-detail/{projectId}/save',
  })
}

/**
 * 删除
 */
export const presaleSupervisionFundsDetailControllerDelete = <ThrowOnError extends boolean = false>(
  options: Options<PresaleSupervisionFundsDetailControllerDeleteData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    PresaleSupervisionFundsDetailControllerDeleteResponse,
    PresaleSupervisionFundsDetailControllerDeleteError,
    ThrowOnError
  >({
    ...options,
    url: '/api/presale-supervision-funds-detail/{projectId}/{id}',
  })
}

/**
 * 列表
 */
export const presaleSupervisionWithdrawableFundsDetailControllerList = <ThrowOnError extends boolean = false>(
  options: Options<PresaleSupervisionWithdrawableFundsDetailControllerListData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PresaleSupervisionWithdrawableFundsDetailControllerListResponse,
    PresaleSupervisionWithdrawableFundsDetailControllerListError,
    ThrowOnError
  >({
    ...options,
    url: '/api/presale-supervision-withdrawable-funds-detail/{projectId}',
  })
}

/**
 * 批量保存
 */
export const presaleSupervisionWithdrawableFundsDetailControllerSave = <ThrowOnError extends boolean = false>(
  options: Options<PresaleSupervisionWithdrawableFundsDetailControllerSaveData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PresaleSupervisionWithdrawableFundsDetailControllerSaveResponse,
    PresaleSupervisionWithdrawableFundsDetailControllerSaveError,
    ThrowOnError
  >({
    ...options,
    url: '/api/presale-supervision-withdrawable-funds-detail/{projectId}/save',
  })
}

/**
 * 删除
 */
export const presaleSupervisionWithdrawableFundsDetailControllerDelete = <ThrowOnError extends boolean = false>(
  options: Options<PresaleSupervisionWithdrawableFundsDetailControllerDeleteData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    PresaleSupervisionWithdrawableFundsDetailControllerDeleteResponse,
    PresaleSupervisionWithdrawableFundsDetailControllerDeleteError,
    ThrowOnError
  >({
    ...options,
    url: '/api/presale-supervision-withdrawable-funds-detail/{projectId}/{id}',
  })
}
