// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch'
import type { UserControllerGetData, UserControllerGetError, UserControllerGetResponse } from './types.gen'

export const client = createClient(createConfig())

export const userControllerGet = <ThrowOnError extends boolean = false>(
  options?: Options<UserControllerGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<UserControllerGetResponse, UserControllerGetError, ThrowOnError>({
    ...options,
    url: '/api/user',
  })
}
