// This file is auto-generated by @hey-api/openapi-ts

export type BaseFilter = {
  /**
   * and查询
   */
  $and?: Array<BaseFilter>
  /**
   * or查询
   */
  $or?: Array<BaseFilter>
  id?:
    | number
    | {
        $eq?: number
        $in?: Array<number>
      }
  createdAt?:
    | Date
    | {
        $in?: Array<Date>
        $eq?: Date
        $like?: Date
        $gt?: Date
        $gte?: Date
        $lte?: Date
        $lt?: Date
      }
  updateAt?:
    | Date
    | {
        $in?: Array<Date>
        $eq?: Date
        $like?: Date
        $gt?: Date
        $gte?: Date
        $lte?: Date
        $lt?: Date
      }
}

export type UserFilter = {
  /**
   * and查询
   */
  $and?: Array<BaseFilter>
  /**
   * or查询
   */
  $or?: Array<BaseFilter>
  id?:
    | number
    | {
        $eq?: number
        $in?: Array<number>
      }
  createdAt?:
    | Date
    | {
        $in?: Array<Date>
        $eq?: Date
        $like?: Date
        $gt?: Date
        $gte?: Date
        $lte?: Date
        $lt?: Date
      }
  updateAt?:
    | Date
    | {
        $in?: Array<Date>
        $eq?: Date
        $like?: Date
        $gt?: Date
        $gte?: Date
        $lte?: Date
        $lt?: Date
      }
  age?:
    | number
    | {
        $in?: Array<number>
        $eq?: number
        $like?: number
        $gt?: number
        $gte?: number
        $lte?: number
        $lt?: number
      }
  account?: {
    [key: string]: unknown
  }
}

export type UserOrderBy = {
  age?: 'asc' | 'desc'
  id?: 'asc' | 'desc'
  createdAt?: 'asc' | 'desc'
  updateAt?: 'asc' | 'desc'
}

export type age = 'asc' | 'desc'

export const age = {
  ASC: 'asc',
  DESC: 'desc',
} as const

export type id = 'asc' | 'desc'

export const id = {
  ASC: 'asc',
  DESC: 'desc',
} as const

export type createdAt = 'asc' | 'desc'

export const createdAt = {
  ASC: 'asc',
  DESC: 'desc',
} as const

export type updateAt = 'asc' | 'desc'

export const updateAt = {
  ASC: 'asc',
  DESC: 'desc',
} as const

export type Role = {
  id: number
  name: string
}

export type User = {
  username: string
  email: string
  role?: Role
  roles?: Array<Role>
  id: number
  createdAt: {
    [key: string]: unknown
  }
  updatedAt: {
    [key: string]: unknown
  }
  createdBy?: number
  updatedBy?: number
}

export type Result = {
  data: Array<User>
  total: number
}

export type UserControllerListData = {
  query?: {
    /**
     * 实际类型为UserFilter，需要使用qs.stringify()
     */
    filter?: string
    name?: string
    /**
     * 实际类型为UserOrderBy，需要使用qs.stringify()
     */
    orderBy?: string
  }
}

export type UserControllerListResponse = Result

export type UserControllerListError = unknown

export type UserControllerPostResponse = User

export type UserControllerPostError = unknown

export type UserControllerUpdateOneResponse = User

export type UserControllerUpdateOneError = unknown

export type UserControllerGetOneData = {
  query: {
    id: string
  }
}

export type UserControllerGetOneResponse = User

export type UserControllerGetOneError = unknown

export type UserControllerDeleteData = {
  query: {
    id: string
  }
}

export type UserControllerDeleteResponse = void

export type UserControllerDeleteError = unknown
