// This file is auto-generated by @hey-api/openapi-ts

export type BaseFilter = {
  /**
   * and查询
   */
  $and?: Array<BaseFilter>
  /**
   * or查询
   */
  $or?: Array<BaseFilter>
  id?:
    | number
    | {
        $eq?: number
        $in?: Array<number>
      }
  createdAt?:
    | Date
    | {
        $in?: Array<Date>
        $eq?: Date
        $like?: Date
        $gt?: Date
        $gte?: Date
        $lte?: Date
        $lt?: Date
      }
  updateAt?:
    | Date
    | {
        $in?: Array<Date>
        $eq?: Date
        $like?: Date
        $gt?: Date
        $gte?: Date
        $lte?: Date
        $lt?: Date
      }
}

export type UserFilter = {
  /**
   * and查询
   */
  $and?: Array<BaseFilter>
  /**
   * or查询
   */
  $or?: Array<BaseFilter>
  id?:
    | number
    | {
        $eq?: number
        $in?: Array<number>
      }
  createdAt?:
    | Date
    | {
        $in?: Array<Date>
        $eq?: Date
        $like?: Date
        $gt?: Date
        $gte?: Date
        $lte?: Date
        $lt?: Date
      }
  updateAt?:
    | Date
    | {
        $in?: Array<Date>
        $eq?: Date
        $like?: Date
        $gt?: Date
        $gte?: Date
        $lte?: Date
        $lt?: Date
      }
  age?:
    | number
    | {
        $in?: Array<number>
        $eq?: number
        $like?: number
        $gt?: number
        $gte?: number
        $lte?: number
        $lt?: number
      }
  account?: {
    [key: string]: unknown
  }
}

export type UserOrderBy = {
  age?: 'asc' | 'desc'
  id?: 'asc' | 'desc'
  createdAt?: 'asc' | 'desc'
  updateAt?: 'asc' | 'desc'
}

export type age = 'asc' | 'desc'

export const age = {
  ASC: 'asc',
  DESC: 'desc',
} as const

export type id = 'asc' | 'desc'

export const id = {
  ASC: 'asc',
  DESC: 'desc',
} as const

export type createdAt = 'asc' | 'desc'

export const createdAt = {
  ASC: 'asc',
  DESC: 'desc',
} as const

export type updateAt = 'asc' | 'desc'

export const updateAt = {
  ASC: 'asc',
  DESC: 'desc',
} as const

export type UserControllerGetData = {
  query?: {
    /**
     * 实际类型为UserFilter，需要使用qs.stringify()
     */
    filter?: string
    name?: string
    /**
     * 实际类型为UserOrderBy，需要使用qs.stringify()
     */
    orderBy?: string
  }
}

export type UserControllerGetResponse = unknown

export type UserControllerGetError = unknown
